version: '3.7'
services:  
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: wechat
      POSTGRES_USER: hernan
      POSTGRES_DB: wechat
    ports:
      - "3000:5432"  
  server:
    build: .
    environment: 
      - NODE_ENV=development
    ports:
      - "3001:3001"
    depends_on:
     - db  
  client:
    build: ../we-chat-client
    volumes:
      - ../we-chat-client:/usr/src/app
    ports:
      - "3002:3000"
    depends_on:
      - server